version: "3"
services:
  db:
    image: mongo
    environment:
      # set username and password  
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    # set port  
    ports:
      - 27017:27017
    # set volume  
    volumes:
      - ./data:/data/db
    restart: always
  api:
    build: ./MiddleEnd
    command: python -u app.py
    volumes:
      - ./MiddleEnd:/usr/src/app
    ports:
      - "5000:5000"
    links:
      - db
  client:
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile
    volumes:
        - /app/node_modules
        - ./FrontEnd:/app
    ports:
        - '8080:8080'
    restart: on-failure
    links:
      - api

      
