version: "3"
services:
  db:
    user: $UID
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: ebuyonline
      MONGO_USERNAME: ebuy
      MONGO_PASSWORD: online
    volumes:
      - ./data:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
  api:
    build: ./MiddleEnd
    command: python -u app.py
    volumes:
      - ./MiddleEnd:/usr/src/app
    ports:
      - "5000:5000"
    links:
      - db
  client:
    build: ./FrontEnd
    volumes:
      - ./FrontEnd:/opt/node_app/app
    ports:
      - "3000:3000"
    links:
      - api
volumes:
  mongodata: